# Generated by Django 3.2 on 2021-04-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('service', models.CharField(choices=[('LINE', 'LINE'), ('MSG', 'Messenger'), ('TG', 'Telegram')], max_length=64)),
                ('paired_rooms', models.ManyToManyField(related_name='_core_room_paired_rooms_+', to='core.Room')),
            ],
        ),
    ]
